<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MachineEquipment" Id="{91f93270-6fb9-4ea3-b10d-5286137dfb51}" SpecialFunc="None">
    <Declaration><![CDATA[/// This function block is a container for equipment that is used by this unit.
/// Equipment is grouped by its kind (actuator, axes, io, ...).
/// It extends from [ManagedObjectContainer](xref:ZCore.ManagedObjectContainer) such that the parent
/// (= the unit itself) can be passed to equipment instances.
FUNCTION_BLOCK MachineEquipment EXTENDS MachineContainer
VAR_INPUT
  Io : MachineIo(_parent);
  Actuator : MachineActuator(_parent);
  Axis : MachineAxis(_parent);
  Fieldbus : MachineFieldbus(_parent);
  Unit : MachineLinkedUnit(_parent);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
